export const AppEnv = {
  authApiUrl: process.env.VUE_APP_AUTHAPI_BASEURL,
  authApiKey: process.env.VUE_APP_AUTHAPI_APIKEY,
  infoApiUrl: process.env.VUE_APP_INFOAPI_BASEURL,
  infoApiKey: process.env.VUE_APP_INFOAPI_APIKEY,
  classroomApiUrl: process.env.VUE_APP_CLASSROOMAPI_BASEURL,
  classroomApiKey: process.env.VUE_APP_CLASSROOMAPI_APIKEY,
  topPageApiUrl: process.env.VUE_APP_TOPPAGEAPI_BASEURL,
  topPageApiKey: process.env.VUE_APP_TOPPAGEAPI_APIKEY,
  topPageImageBaseUrl: process.env.VUE_APP_TOPPAGE_IMAGE_BASEURL,
  albumApiUrl: process.env.VUE_APP_ALBUMAPI_BASEURL,
  albumApiKey: process.env.VUE_APP_ALBUMAPI_APIKEY,
  FIREBASE_API_KEY: process.env.VUE_APP_FIREBASE_API_KEY,
  FIREBASE_AUTH_DOMAIN: process.env.VUE_APP_FIREBASE_AUTH_DOMAIN,
  FIREBASE_DATABASE_URL: process.env.VUE_APP_FIREBASE_DATABASE_URL,
  FIREBASE_PROJECT_ID: process.env.VUE_APP_FIREBASE_PROJECT_ID,
  FIREBASE_STORAGE_BUCKET: process.env.VUE_APP_FIREBASE_STORAGE_BUCKET,
  FIREBASE_MESSAGING_SENDER_ID:
    process.env.VUE_APP_FIREBASE_MESSAGING_SENDER_ID,
  FIREBASE_APP_ID: process.env.VUE_APP_FIREBASE_APP_ID
};
